INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-01-01','New Year Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-03-29','Good Friday');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-04-01','Easter Monday');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-05-22','Victoria Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-07-01','Canada Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-08-05','Civic Holiday');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-09-02','Labour Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-09-30','National Day for Truth and Reconciliation');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-10-14','Thanksgiving Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-11-11','Remembrance Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-12-25','Christmas Day');
INSERT INTO holiday (name,date,country) VALUES ('CANADA','2024-12-26','Boxing Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-01-01','New Year Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-01-15','Birthday of Martin Luther King, Jr.');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-02-19','Washingtons Birthday');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-05-27','Memorial Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-06-19','Juneteenth National Independence Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-07-04','Independence Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-09-02','Labour Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-10-14','Columbus Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-11-11','Veterans Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-11-28','Thanksgiving Day');
INSERT INTO holiday (name,date,country) VALUES ('USA','2024-12-25','Christmas Day');